### ISSUE TITLE
undefined method `rsocialize_div_tag'

### ISSUE THREAD

**Issue by tballarin** [treble37/rsocialize#11]
Hi, 

 I have made installation of gem and when I add `rsocialize_div_tag' and `rsocialize_js_tag' I have this error
undefined method `rsocialize_div_tag'

You have an other problem during uninstall of Gem, you delete all assets/images/folder :(

**Comment by treble37** [comment]
@tballarin, can you give a bit more detail on `rsocialize_div_tag` error?  Or do you have a sample app with the code that I can download and look at?  For instance at https://github.com/treble37/rsocialize_app in app/views/users/index.html.erb I do the same thing you do and it's working for me.  I'll look at the uninstall issue.

**Comment by treble37** [comment]
@tballarin version 0.0.5 fixes the delete of the assets/images/folder on uninstall....
